In [1]:
import math

In [4]:
num = int(input("Enter a number: "))
num

Enter a number:  121


121

In [5]:
math.sqrt(num)

11.0

In [6]:
math.sqrt(9)

3.0

In [7]:
math.pow(3,2)

9.0

In [7]:
3 ** 2

9

In [8]:
math.ceil(1.2)

2

In [9]:
math.ceil(1.7)

2

In [10]:
math.floor(1.2)

1

In [11]:
math.floor(1.7)

1

In [8]:
import math as m

In [9]:
m.sqrt(9)

3.0

# Numpy 

- Numerical Python > Library used for complex mathematical operations fastly. 

In [12]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
import numpy as np

In [1]:
list1 = [1,2,3,4]
arr1 = np.array(list1)

NameError: name 'np' is not defined

In [2]:
print(f"arr1: {arr1}, datatype: {type(arr1)}")

NameError: name 'arr1' is not defined

In [16]:
ar_list = [1,2,3,4]
print(f"ar_list: {ar_list}, datatype: {type(ar_list)}")

ar_list: [1, 2, 3, 4], datatype: <class 'list'>


### creating array from list

In [16]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

1D array:  [1 2 3 4 5]


In [8]:
# 2d list
abc = [[1,2,3], [4,5,6]]
print(abc)

[[1, 2, 3], [4, 5, 6]]


In [17]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

2D array:  [[1 2 3]
 [4 5 6]]


In [18]:
# Make the array `my_array`
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_array`
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
# Using arange
arr3 = np.arange(0, 10, 2)  # start, stop, step
print("arange:", arr3)

arange: [0 2 4 6 8]


In [24]:
# Using linspace
arr4 = np.linspace(0, 10, 3)  # 2 values between 0 and 10
print("linspace:", arr4)

linspace: [ 0.  5. 10.]


In [25]:
# Using linspace
arr4 = np.linspace(0, 20, 3)  # 3 values between 0 and 20
print("linspace:", arr4)

linspace: [ 0. 10. 20.]


### List vs numpy array


In [25]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [26]:
import time
start = time.time()

# for i in range(1000000):
    # i*2 

py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.13472843170166016

 Numpy operation time:  0.006861209869384766


In [28]:
current_time = time.time() 
print("Current time in seconds since epoch:", current_time)


Current time in seconds since epoch: 1762777535.050067


### creating array from scratch

In [29]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)


one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.02894914 0.44408507 0.31819281]
 [0.11939368 0.170423   0.45646147]]
sequnce array: 
 [ 0  2  4  6  8 10]


In [32]:
# Identity matrix
eye = np.eye(4)
print("Identity matrix:\n", eye)

# Random values
rand = np.random.rand(2, 3)  # values in [0, 1)
print("Random:\n", rand)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random:
 [[0.3830068  0.29404819 0.6995299 ]
 [0.63195942 0.99044974 0.44037664]]


# Array Attributes

In [27]:
a = np.array([[1, 2, 3], [4, 5.5, 6]])
print(a)
print("Shape:", a.shape)       # (2, 3)
print("Size:", a.size)         # 6
print("Dimensions:", a.ndim)   # 2
print("Data type:", a.dtype)   # int32 or int64 depending on system

[[1.  2.  3. ]
 [4.  5.5 6. ]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: float64


### Vector, Matrix and Tensor

In [35]:
# vector = 1d
# matrix = 2d
# Tensor = nd
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2, 44], [3, 4, 55]], 
                   [[5, 6, 66], [7, 8, 88]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[ 1  2 44]
  [ 3  4 55]]

 [[ 5  6 66]
  [ 7  8 88]]]


In [28]:
print(tensor.shape)
print(tensor.size)
tensor.ndim

(2, 2, 3)
12


3

In [59]:
tensor.shape

(2, 2, 3)

### Array properties

In [29]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [32]:
arr = np.arange(12)
print("Original array ", arr, "Shape: ", arr.shape)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped, "Shape: ", reshaped.shape)

flattened = reshaped.flatten() # Convert multi-dimensional array to 1D
print("\n Flattened array ", flattened, )

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11] Shape:  (12,)

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] Shape:  (3, 4)

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Indexing and Slicing

In [63]:
a = [[10, 20, 30], [40, 50, 60]]  # List

print(a[0][1])  # 20
print(a[1])     # [40 50 60]
print(a[:][1])  # column 1: [20 50]
print(a[0:2][1:])  # rows 0-1, cols 1-2

20
[40, 50, 60]
[40, 50, 60]
[[40, 50, 60]]


In [64]:
a = np.array([[10, 20, 30], [40, 50, 60]])

print(a[0, 1])  # 20
print(a[1])     # [40 50 60]
print(a[:, 1])  # column 1: [20 50]
print(a[0:2, 1:])  # rows 0-1, cols 1-2


20
[40 50 60]
[20 50]
[[20 30]
 [50 60]]


# Array Operations

In [35]:
a = [1, 2, 3]
b = [4, 5, 6]

print("Add:", a + b) # merge
# print("Multiply:", a * b) # not supported
# print("Power:", a ** 2)


Add: [1, 2, 3, 4, 5, 6]


In [67]:
# Element-wise operations:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Add:", a + b)
print("Multiply:", a * b)
print("Power:", a ** 2)
print("Sin:", np.sin(a))
print("Log:", np.log(a))


Add: [5 7 9]
Multiply: [ 4 10 18]
Power: [1 4 9]
Sin: [0.84147098 0.90929743 0.14112001]
Log: [0.         0.69314718 1.09861229]


In [16]:
a = [1, 2, 3]
b = [4, 5, 6]
a+b

[1, 2, 3, 4, 5, 6]

In [68]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print("Matrix product:\n", A @ B)  # OR np.dot(A, B)


Matrix product:
 [[ 4  4]
 [10  8]]


In [69]:
x = np.array([[1, 2, 3], [3, 4, 5]])
y = np.array([6,7,8])

# Add `x` and `y`
z = np.add(x,y)
print("Addition of x and y:\n", z)

# Subtract `x` and `y`
z = np.subtract(x,y)
print("Subtraction of y from x:\n", z)

# Multiply `x` and `y`
z = np.multiply(x,y)
print("Element-wise multiplication of x and y:\n", z)

Addition of x and y:
 [[ 7  9 11]
 [ 9 11 13]]
Subtraction of y from x:
 [[-5 -5 -5]
 [-3 -3 -3]]
Element-wise multiplication of x and y:
 [[ 6 14 24]
 [18 28 40]]


# Subset, Slice, and Index Arrays

In [22]:
# Subsetting

import numpy as np

# Initialize 1D array
my_array = np.array([1,2,3,4])

# Print subsets
print(my_array[1])


2


In [23]:
import numpy as np

# Initialize 2D array
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print subsets
print(my_2d_array[1][2])
print(my_2d_array[1,2])

7
7


In [24]:
import numpy as np

# Initialize 3D array
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], 
                        [[1,2,3,4], [9,10,11,12]]], dtype=np.int64)

# Print subset
print(my_3d_array[1,1,2])

11


# Slicing

In [25]:
import numpy as np

# Initialize 1D array
my_array = np.array([1,2,3,4])

# Print subsets
print(my_array[0:2])

[1 2]


In [71]:
import numpy as np

# Initialize 2D array
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print subsets
print(my_2d_array[0:2,1])

[2 6]


# Filtering, Boolean Indexing

In [73]:
import numpy as np
my_array = np.array([1,2,3,4])
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]], dtype=np.int64)

# Try out a simple example
print(my_array[my_array<3])

# Specify a condition
bigger_than_3 = (my_3d_array >= 3)

# Use the condition to index our 3d array
print(my_3d_array[bigger_than_3])

[1 2]
[ 3  4  5  6  7  8  3  4  9 10 11 12]


# Useful Functions

In [74]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(a))               # sum of all
print("Column-wise sum:", a.sum(axis=0))  # [5 7 9]
print("Row-wise max:", a.max(axis=1))     # [3 6]
print("Mean:", a.mean())
print("Standard Deviation:", a.std())


Sum: 21
Column-wise sum: [5 7 9]
Row-wise max: [3 6]
Mean: 3.5
Standard Deviation: 1.707825127659933


In [75]:
a = np.array([1, 2, np.nan, 4])

print("Is NaN:", np.isnan(a))
print("Mean (ignoring NaN):", np.nanmean(a))


Is NaN: [False False  True False]
Mean (ignoring NaN): 2.3333333333333335


# Broadcasting

In [19]:
a = np.array([1, 2, 3])
b = 2

print("Multiply:", a * b)  # [2 4 6]

Multiply: [2 4 6]


In [20]:
a = [1, 2, 3]
b = 2

print("Multiply:", a * b)  # [2 4 6]

Multiply: [1, 2, 3, 1, 2, 3]


In [30]:
# Get info on data types with `np.info()`
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Reshaping vs Resizing in NumPy

| Feature                | `reshape()`                           | `resize()`                          |
| ---------------------- | ------------------------------------- | ----------------------------------- |
| **Modifies original?** | ❌ No (returns a new view if possible) | ✅ Yes (modifies the original array) |
| **Keeps data?**        | ✅ Keeps all data (must fit new shape) | ✅ Can add/remove elements           |
| **Returns**            | New array (view or copy)              | Nothing (modifies in-place)         |
| **Raises Error?**      | ✅ If shape is incompatible            | ❌ Fills with 0 if expanding         |



# reshape() – Non-destructive, Flexible View
- Creates a new view or copy of the original array.

- Does not change the original array.

- The total number of elements must remain the same.

In [32]:
import numpy as np

a = np.arange(6)        # [0 1 2 3 4 5]
b = a.reshape((2, 3))   # 2 rows, 3 columns

print("Original:", a)
print("Reshaped:\n", b)


Original: [0 1 2 3 4 5]
Reshaped:
 [[0 1 2]
 [3 4 5]]


In [33]:
# Error if incompatible shape:

a = np.arange(5)
b = a.reshape((2, 3))  # Error! 5 elements can't reshape to 2x3


ValueError: cannot reshape array of size 5 into shape (2,3)

# resize() – In-place, Size-changing

- Modifies the original array in-place.

- Can increase or decrease the number of elements.

- When enlarging, new elements are filled with 0.

In [38]:
a = np.array([1, 2, 3])
print(f"before resising: {a}")
a.resize((2, 3))  # Add 3 more elements (filled with 0)
print(a)

before resising: [1 2 3]
[[1 2 3]
 [0 0 0]]


In [37]:
# Decreasing Elements
a = np.arange(6)
print(f"before resising: {a}")
a.resize((2, 2))  # Truncates values to fit new size
print(a)

before resising: [0 1 2 3 4 5]
[[0 1]
 [2 3]]


| Feature             | `reshape()`                   | `resize()`            |
| ------------------- | ----------------------------- | --------------------- |
| Modifies original?  | No                            | Yes                   |
| Shape flexibility   | Must match total size         | Can shrink or grow    |
| Fills new elements? | Not applicable                | Yes, fills with zeros |
| Use-case            | Rearranging without data loss | Changing total size   |


# Try these tasks:

Create a 4x4 array of random numbers and calculate its mean and max.

Make a 1D array of 10 numbers and reshape it to (2, 5).

Use broadcasting to add a row vector to a 2D array.

In [39]:
# Solution

In [43]:
# Task 1
import numpy as np

# Create a 4x4 array of random numbers between 0 and 1
arr = np.random.rand(4, 4)

print("4x4 Random Array:\n", arr)

# Calculate mean and max
mean_val = np.mean(arr)
max_val = np.max(arr)

print("\nMean of the array:", mean_val)
print("Max of the array:", max_val)


4x4 Random Array:
 [[0.40487836 0.66295906 0.22027589 0.6156715 ]
 [0.15485189 0.36253238 0.24426913 0.59694659]
 [0.46568981 0.38395849 0.12935957 0.36701566]
 [0.64462334 0.38098791 0.79849881 0.15824455]]

Mean of the array: 0.41192268418815836
Max of the array: 0.7984988139282463


In [41]:
# Task 2

# Create 1D array of 10 numbers
arr_1d = np.arange(10)

print("Original 1D Array:", arr_1d)

# Reshape to 2 rows, 5 columns
arr_reshaped = arr_1d.reshape(2, 5)

print("\nReshaped to 2x5:\n", arr_reshaped)


Original 1D Array: [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [42]:
# Task 3

# Create a 2D array (3x4)
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Create a row vector of shape (4,)
row_vec = np.array([10, 20, 30, 40])

# Broadcasting addition
result = matrix + row_vec

print("Original Matrix:\n", matrix)
print("Row Vector:\n", row_vec)
print("After Broadcasting (Matrix + Row Vector):\n", result)


Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Row Vector:
 [10 20 30 40]
After Broadcasting (Matrix + Row Vector):
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]
